version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: backend_dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./hls_streams:/app/hls_streams
    environment:
      - GOPRO_CONFIG_FILE = "./config/gopro_config.json"
      - HLS_DIR = "./hls_streams"

  frontend:
    build:
      context: ./frontend
      dockerfile: frontend_dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    # environment:
    #   - CHOKIDAR_USEPOLLING=true
