version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: backend_dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - GOPRO_CONFIG_FILE: "./backend/config/gopro_config.json"

  frontend:
    build:
      context: ./frontend
      dockerfile: frontend_dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    # environment:
    #   - CHOKIDAR_USEPOLLING=true
